apiVersion: apps/v1 
kind: Deployment
metadata:
  name: anagramapp-deployment
spec:
  selector:
    matchLabels:
      app: anagramapp
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: anagramapp
    spec:
      containers:
      - name: anagram-container
        image: mozubayer/anagram-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
