apiVersion: v1
kind: Service
metadata:
  name: anagramapp-service
  labels:
    app: anagramapp
spec:
  selector:
    app: anagramapp
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32001
